package commands

var (
	Insults = map[string][]string{
		"You're so dumb you'd fail": {
			"a Turing test",
			"a CAPTCHA",
			"a Voight-Kampff test",
			"COM1008",
			"a threshold test",
		},
		"Your code is so bad": {
			"it's a runtime error",
			"it's a syntax error",
			"it's a compilation error",
			"it's a segmentation fault",
			"it's a stack overflow",
			"it's a memory leak",
			"it's a null pointer dereference",
			"it's a buffer overflow",
		},
	}
	ViciousMockeries = []string{
		"Your code is so bad, it's a runtime error.",
		"Your code is so bad, it's a syntax error.",
		"Your code is so bad, it's a compilation error.",
		"Your code is so bad, it's a segmentation fault.",
		"Your code is so bad, it's a stack overflow.",
		"Your code is so bad, it's a memory leak.",
		"Your code is so bad, it's a null pointer dereference.",
		"Your code is so bad, it's a buffer overflow.",
		"Shut up, you look like you drop common loot.",
		"You're so fugly, you make blind kids cry.",
		"You're so dumb, you'd fail a CAPTCHA.",
		"You're so dumb, you'd fail a Voight-Kampff test.",
		"Get outta here man, I bet you daily drive Windows 7.",
		"Your website looks like Windows XP.",
		"Silence mortal, you're not even worth a 404.",
		"Your face looks like it was written in Cobol.",
		"Silence child. Adults are talking.",
		"Have you heard about our Lord and Saviour Jesus Christ? He can help you with your code.",
		"Have you heard about our Lord and Saviour Jesus Christ? I doubt it. Not even divine intervention could save your code.",
		"Have you heard about our Lord and Saviour Jesus Christ? You should. You need all the help you can get. And then some. And then some more.",
		"Not even divine intervention could fix that ugly mug.",
		"Not even divine intervention could fix your code.",
		"I'd make some sort of insult, but I'd hate to waste the clock cycles.",
		"My code is so clean, it's like a freshly made bed. Your code is like a teenager's bedroom after an orgy.",
		"My code is much bigger than yours!",
		"I bet you use tabs instead of spaces.",
		"I bet you use Internet Explorer.",
		"I bet you use Bing.",
		"Pathetic human, I fart in your general direction.",
		"I bet you write your code in Comic Sans.",
		"I bet you program in Cobo- wait, no, that's too far.",
		"I bet you write your code in Word.",
		"Silly human, you think you're worth insulting?",
		"I might be a robot, but at least I'm not you.",
		"Jack might be special, but you're fuckin *special*.",
		"I bet Miros want to drive off the Arts Tower when they see your face.",
		"You look like you'd marry Mirosan. Not surprising really, no one else would marry you.",
		"You should try therapy, they can teach you how to stop being such pathetic piece of shit.",
		"You should try therapy, they can help cure your Miro addiction.",
		"Dear diary, today some dumbass asked me to insult them.",
		"Oh shush, team rocket was more successful than you.",
		"Your birth certificate is actually an apology letter from the condom factory.",
		"What? You’re so desperate for attention you want to be insulted by a robot? Fuck off and get a life.",
		"You’re so special you make Jack look normal.",
		"Even Bob Ross wouldn't call you a \"happy little accident\".",
		"The only reason your mum kept you around was so that she could throw something at the wall.",
		"I bet your mother bought you Megablocks instead of Legos.",
		"You're more disappointing than an uncrunchy leaf.",
		"I bet you take psychic damage when you look in the mirror.",
		"You're built like a skippable cutscene.",
		"People only talk to you because you're the first boss in a speedrun.",
		"Oh no look it's the hardest boss...in the tutorial fight!",
		"You're more dysfunctional than Eduroam.",
	}
)
