name: Docker Build
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Ensure repo name is lowercase
        run: |
          echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Triggered by every commit
      # Creates images for the commit's hash and branch name
      - name: Push to commit hash and branch name
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            version=${{ github.dev }}
            revision=${{ github.sha }}
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }},ghcr.io/${{ env.REPO }}:${{ github.ref_name }}
        if: ${{ github.ref_type == 'branch' }}

      # Only triggered by commits to tags
      # Creates images for the tag name only
      - name: Push to tag name only
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            version=${{ github.ref_name }}
            revision=${{ github.sha }}
          tags: ghcr.io/${{ env.REPO }}:${{ github.ref_name }}
        if: ${{ github.ref_type == 'tag' && github.event_name == 'push' }}

      # Only triggered when a release is published
      # Creates images for the tag name and the latest tag
      - name: Push to tag name and latest
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            version=${{ github.ref_name }}
            revision=${{ github.sha }}
          tags: ghcr.io/${{ env.REPO }}:${{ github.ref_name }},ghcr.io/${{ env.REPO }}:latest
        if: ${{ github.event_name == 'release' }}